sudo: false
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
services:
  - mongodb
  - rabbitmq
  - redis-server
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install --frozen-lockfile
  - yarn global add coveralls
script:
  - yarn run test:ci
after_success:
  - cat ./coverage/lcov.info | coveralls
cache:
  yarn: true
  directories:
    - packages/amqp/node_modules
    - packages/core/node_modules
    - packages/express/node_modules
    - packages/graphql-core/node_modules
    - packages/graphql-express/node_modules
    - packages/graphql-koa/node_modules
    - packages/koa/node_modules
    - packages/log4js/node_modules
    - packages/mongoose/node_modules
    - packages/typeorm/node_modules
branches:
  only:
    - master
    - v8
