language: node_js
node_js:
  - "7"
  - "node"
services:
  - rabbitmq
install:
  - yarn
  - npm install -g codecov
script:
  - npm test -- --coverage
  - node remap_coverage.js
  - rm -fr coverage_jest_raw
  - codecov
